In [1]:
import pyroms

scrip.so not found. Remapping function will not be available


In [13]:
import numpy as np
xbry = [0,0,5,5]
ybry = [5,0,0,5]
beta = [1,1,1,1]
shape = (20,20)

grd = pyroms.grid.ROMS_Grid("ob500")

In [24]:
s = grd.vgrid(np.array([10, 5]), 0, 3, 0.5, 20)

In [27]:
grd.hgrid?

In [29]:
x, y = np.mgrid[0.0:7.0, 0.0:8.0]
x = np.ma.masked_where( (x<3) & (y<3), x)
y = np.ma.MaskedArray(y, x.mask)
grd = pyroms.grid.CGrid(x, y)
grd.x_rho

masked_array(data =
 [[-- -- -- 0.5 0.5 0.5 0.5]
 [-- -- -- 1.5 1.5 1.5 1.5]
 [-- -- -- 2.5 2.5 2.5 2.5]
 [3.5 3.5 3.5 3.5 3.5 3.5 3.5]
 [4.5 4.5 4.5 4.5 4.5 4.5 4.5]
 [5.5 5.5 5.5 5.5 5.5 5.5 5.5]],
             mask =
 [[ True  True  True False False False False]
 [ True  True  True False False False False]
 [ True  True  True False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]],
       fill_value = 1e+20)

In [30]:
grd.name = "test"

In [32]:
pyroms.grid.write_ROMS_grid(grd, "test_grd.nc")

AttributeError: 'CGrid' object has no attribute 'hgrid'

In [ ]:
grd.